---
on:
  workflow_call: {}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

permissions: read-all

jobs:
  pr-title-validation:
    uses: ./.github/workflows/sub-pr-title-validation.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› ï¸ Setup
        uses: ./.github/workflows/sub-setup.yaml

      - name: ğŸ—ï¸ Build
        run: npm run build

  code-review:
    uses: ./.github/workflows/sub-code-review.yaml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  trufflehog:
    uses: ./.github/workflows/sub-trufflehog.yaml

  cypress:
    uses: ./.github/workflows/sub-cypress.yaml
    secrets: inherit

  lint:
    uses: ./.github/workflows/sub-linting.yaml

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› ï¸ Setup
        uses: ./.github/workflows/sub-setup.yaml

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
